export const initialConferences = [
    {
        name: "TAIS 2026",
        deadline: "2026-01-31",
        location: "Oxford, UK",
        dates: "May 14, 2026",
        description: "Free, 1-day technical AI safety workshop at Oxford Martin School. Run by Oxford Martin AI Governance Initiative & Noeon Research.",
        requirements: "Short papers (max 8 pages). Non-archival.",
        link: "https://tais2026.cc",
        category: "safety",
        status: "open",
        confidence_score: "medium" as const
    },
    {
        name: "FAccT 2026",
        deadline: "2026-01-13",
        abstract_deadline: "2026-01-08",
        location: "Montreal, Canada",
        dates: "June 2026",
        description: "ACM Fairness, Accountability, Transparency. Interdisciplinary: CS, law, philosophy, social science.",
        requirements: "Up to 14 pages (ACM format). Archival/non-archival options.",
        link: "https://facctconference.org/2026/cfp.html",
        category: "ethics",
        status: "open",
        confidence_score: "high" as const
    },
    {
        name: "IJCAI-ECAI 2026",
        deadline: "2026-01-19",
        abstract_deadline: "2026-01-12",
        location: "Bremen, Germany",
        dates: "Aug 15-21, 2026",
        description: "Premier joint AI conference. Special tracks: Human-Centered AI, AI for Social Good, AI & Health, AI & Robotics.",
        requirements: "7 pages + 2 refs. $100 fee (waived for primary papers). Two-phase review.",
        link: "https://2026.ijcai.org/",
        category: "ml",
        status: "open",
        confidence_score: "high" as const
    },
    {
        name: "ICML 2026 (Main)",
        deadline: "2026-01-28",
        abstract_deadline: "2026-01-23",
        location: "Seoul, Korea",
        dates: "Jul 6-11, 2026",
        description: "Premier ML conference. Broad ML including safety, alignment, robustness.",
        requirements: "8 pages + unlimited refs/appendices. Double-blind on OpenReview.",
        link: "https://icml.cc/Conferences/2026/CallForPapers",
        category: "ml",
        status: "open",
        confidence_score: "high" as const
    },
    {
        name: "ICML 2026 (Position)",
        deadline: "2026-01-28",
        abstract_deadline: "2026-01-23",
        location: "Seoul, Korea",
        dates: "Jul 6-11, 2026",
        description: "Position/perspective papers on ML field direction. Good for meta-level arguments about safety approaches.",
        requirements: "Same format as main track. Select 'Position Paper Track.'",
        link: "https://icml.cc/Conferences/2026/CallForPositionPapers",
        category: "ml",
        status: "open",
        confidence_score: "high" as const
    },
    {
        name: "ACL 2026",
        deadline: "2026-01-05",
        location: "San Diego, CA",
        dates: "Jul 2-7, 2026",
        description: "Premier NLP conference. Theme: Explainability of NLP Models. Uses ACL Rolling Review.",
        requirements: "8 pages (long) / 4 pages (short) + refs. Through ARR system.",
        link: "https://2026.aclweb.org/calls/main_conference_papers/",
        category: "nlp",
        status: "open",
        confidence_score: "high" as const
    },
    {
        name: "IEEE WCCI 2026",
        deadline: "2026-01-31",
        location: "Maastricht, Netherlands",
        dates: "Jun 21-26, 2026",
        description: "World Congress on Computational Intelligence. Includes IJCNN, FUZZ-IEEE, IEEE CEC.",
        requirements: "IEEE format. Dual format (in-person + online).",
        link: "https://attend.ieee.org/wcci-2026/",
        category: "ml",
        status: "open",
        confidence_score: "high" as const
    },
    {
        name: "COLM 2026",
        deadline: "2026-03-31",
        abstract_deadline: "2026-03-26",
        location: "San Francisco, CA",
        dates: "Oct 6-9, 2026",
        description: "Conference on Language Modeling. Focused on LLM research: training, safety, evaluation, scalable oversight.",
        requirements: "9 pages + unlimited refs. Single-track. OpenReview.",
        link: "https://colmweb.org/cfp.html",
        category: "safety",
        status: "open",
        confidence_score: "high" as const
    },
    {
        name: "NeurIPS 2026",
        deadline: "2026-05-15",
        location: "Sydney, Australia",
        dates: "Dec 6-12, 2026",
        description: "Premier ML conference. Broad ML + safety tracks.",
        requirements: "9 pages + refs/checklist. Double-blind on OpenReview.",
        link: "https://neurips.cc/Conferences/2026/Dates",
        category: "ml",
        status: "open",
        confidence_score: "medium" as const
    },
    {
        name: "EMNLP 2026",
        deadline: "2026-05-25",
        location: "Budapest, Hungary",
        dates: "Oct 24-29, 2026",
        description: "NLP conference. Empirical methods in NLP.",
        requirements: "Uses ACL Rolling Review. Long/short paper options.",
        link: "https://x.com/emnlpmeeting",
        category: "nlp",
        status: "open",
        confidence_score: "medium" as const
    },
    {
        name: "SAFECOMP 2026",
        deadline: "2026-04-15",
        location: "Valencia, Spain",
        dates: "Sep 22-25, 2026",
        description: "Safety-critical systems. Theme: 'Engineering safe and sustainable computing systems.'",
        requirements: "Regular papers + position papers. LNCS format.",
        link: "https://safecomp2026.webs.upv.es/",
        category: "safety",
        status: "open",
        confidence_score: "medium" as const
    },
    {
        name: "AIES 2026",
        deadline: "2026-05-01",
        location: "TBA",
        dates: "Fall 2026",
        description: "AAAI/ACM AI, Ethics, and Society. Ethics, societal impact of AI.",
        requirements: "10 pages (AAAI format). Interdisciplinary.",
        link: "https://www.aies-conference.com/",
        category: "ethics",
        status: "open",
        confidence_score: "medium" as const
    },
    {
        name: "EAAMO 2026",
        deadline: "2026-04-24",
        location: "TBA",
        dates: "Fall 2026",
        description: "ACM Equity & Access in Algorithms, Mechanisms, Optimization.",
        requirements: "Archival/non-archival. Up to 14 pages.",
        link: "https://conference.eaamo.org/cfp/",
        category: "ethics",
        status: "open",
        confidence_score: "medium" as const
    },
    {
        name: "ICLR 2026",
        deadline: "2025-09-24",
        location: "Rio de Janeiro, Brazil",
        dates: "Apr 23-27, 2026",
        description: "Learning representations. Broad ML + safety/ethics.",
        requirements: "9 pages + refs. OpenReview with public discussion.",
        link: "https://iclr.cc/Conferences/2026/CallForPapers",
        category: "ml",
        status: "passed",
        confidence_score: "high" as const
    },
    {
        name: "AAAI 2026 (AI Alignment)",
        deadline: "2025-08-01",
        location: "Singapore",
        dates: "Jan 20-27, 2026",
        description: "Scalable oversight, mechanistic interpretability, robustness, red-teaming, safe-by-design, formal safety cases.",
        requirements: "Same as main track. Select 'AI Alignment (AIA)' track.",
        link: "https://aaai.org/conference/aaai/aaai-26/aia-call/",
        category: "safety",
        status: "passed",
        confidence_score: "high" as const
    },
    {
        name: "AAMAS 2026",
        deadline: "2025-10-08",
        location: "Paphos, Cyprus",
        dates: "May 25-29, 2026",
        description: "Autonomous Agents & Multi-Agent Systems. Includes COINE track (norms, ethics, safety).",
        requirements: "8 pages + refs. Blue Sky Ideas track available.",
        link: "https://cyprusconferences.org/aamas2026/",
        category: "ml",
        status: "passed",
        confidence_score: "high" as const
    },
    {
        name: "CVPR 2026",
        deadline: "2025-11-13",
        location: "Denver, CO",
        dates: "Jun 3-7, 2026",
        description: "Computer Vision & Pattern Recognition. Vision + ML safety/robustness topics.",
        requirements: "8 pages + refs. OpenReview. Code encouraged.",
        link: "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
        category: "ml",
        status: "passed",
        confidence_score: "high" as const
    },
    {
        name: "IASEAI 2026",
        deadline: "Rolling",
        location: "Paris, France (UNESCO)",
        dates: "Feb 24-26, 2026",
        description: "International Association for Safe & Ethical AI. AI safety, ethics, governance. Invitation-only.",
        requirements: "Talk proposals on rolling basis. Statement of Interest open.",
        link: "https://www.iaseai.org/iaseai26",
        category: "safety",
        status: "rolling",
        confidence_score: "high" as const
    }
];
